enum class PlayTeam
{
	NONE = 0,
	CIRCLES = 1,
	SQUARES = 2
};

enum class GameState
{
	STOP = 0,
	MAIN_MENU = 1,
	FIELD_MENU = 2,
	PLAYERS_MENU = 3,
	TEAM_MENU = 4,
	PREGAMEPLAY = 5,
	GAMEPLAY = 6,
	RESULT = 7
};

enum class GameMode
{
	IDLE = 0,
	SMALL_FIELD = 1,
	LARGE_FIELD = 2,
	PLAYER_VS_PLAYER = 4,
	PLAYER_VS_AI = 8,
	AI_VS_AI = 16,

	STANDART_PVP  = SMALL_FIELD | PLAYER_VS_PLAYER,
	STANDART_SOLO = SMALL_FIELD | PLAYER_VS_AI,
	STANDART_AUTO = SMALL_FIELD | AI_VS_AI,

	EXTENDED_PVP  = LARGE_FIELD | PLAYER_VS_PLAYER,
	EXTENDED_SOLO = LARGE_FIELD | PLAYER_VS_AI,
	EXTENDED_AUTO = LARGE_FIELD | AI_VS_AI
};